# Generated by Django 3.0.7 on 2020-10-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_payment_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='item',
        ),
    ]
