# Generated by Django 3.0.7 on 2020-10-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20201021_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='images',
            new_name='image',
        ),
    ]
